version: '2.3'
services:
  python-test:
    build:
      context: ./stac-client
      dockerfile: Dockerfile.test
    links:
      - franklin:franklin.service.internal
  franklin:
    environment:
      - DB_NAME=franklin-test
  database:
    environment:
      - POSTGRES_DB=franklin-test
