FROM python:3.9-slim-buster

RUN mkdir -p /opt/src

WORKDIR /opt/src

COPY requirements.test.txt /opt/src
RUN pip install -r requirements.test.txt

COPY requirements.txt /opt/src
RUN pip install -r requirements.txt

COPY ./ /opt/src/

ENTRYPOINT ["pytest"]
