---
title: Create AMI and Launch New Instance
output: 
  github_document:
    toc: true
---

***
<center>
[Back to **index**](../README.md)
</center>
***

## Creating an instance template{#creating-an-instance-template}

This picks up from the previous section on starting and configuring a `jupyter notebook` capable instance with a working version of `imager` installed. Now 
we walk through the process of creating an image from that pre-configured instance (documentation for that is under airgresources), and then launching a new and more capable instance from that image, with more processing power and a larger disk size. 

## Create an AMI of an existing instance

First, get the instance ID of the existing image. You can find that easily in the EC2 console, or simply run this:
```bash
INAME=planet-compositer
IID=`aws ec2 describe-instances --filters 'Name=tag:Name,Values='"$INAME"'' \
--output text --query 'Reservations[*].Instances[*].InstanceId'`
echo $IID
```

Then you can run the following, replace the `instance_name` variables with something new (e.g. imager-ami) and some sort of informative description (e.g. 30gb-imager-ami)
```bash
# instance ID of disk you want to image
# IID=<instance_id>  # uncomment & insert manually copied instance ID if needed 
instance_name=<instance_name>
description=<description>
aws ec2 create-image --instance-id $IID --name $instance_name --description $description
```

## Launch new instance

From the AMI you just made, create a new instance, but:

- Use a more capacious instance type (t2.2xlarge)
- Resize the volume to make it larger. Solution for increasing volume size from [here](http://blog.xi-group.com/2014/06/small-tip-use-aws-cli-to-create-instances-with-bigger-root-partitions/). 
- Attach an IAM role to allow S3 access. The code for this is from [here](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/iam-roles-for-amazon-ec2.html#launch-instance-with-role). The following set of commands will set 

The following `bash` commands will get you there. An example of the variable values will be provided separately:
```bash
AMIID=<ami-id>
ITYPE=<instance type>
KEYNAME=<key_pair>
SECURITY=<security_group>
INAME=<new instance name>
OWNER=<owner>
SDASIZE=<volume size in gb>
IAM=<iam role name>

aws ec2 run-instances --image-id $AMIID --count 1 --instance-type $ITYPE --iam-instance-profile Name=$IAM --key-name $KEYNAME --security-groups $SECURITY  --block-device-mapping "[ { \"DeviceName\": \"/dev/sda1\", \"Ebs\": { \"VolumeSize\": $SDASIZE } } ]" --tag-specifications 'ResourceType=instance,Tags=[{Key=Name,Value='$INAME'}]' 'ResourceType=volume,Tags=[{Key=Owner,Value='$OWNER'}]' 
```

Once you execute that, a new instance will spin up, and you will be able to SSH in to that and start working with it, following the same notebook connection and `ssh` procedures as detailed in [our previous page](start-configure-imager.md)

***
<center>
[Back to top](#creating-an-instance-template) || [Back to **index**](../README.md)
</center>
***
