imagery:
  aoiid: GH0421189_GH0493502_dl_test
  cellgrid_buffer: 0.05
  # tile_object and grids_tile_filename should be changed 
  # for different study area, e.g. ghana
  tile_object: planet/grids_geojson/ghana_tiles.geojson
  grids_tile_filename: grids_tile_ghana.csv
  master_grid_object: grid/master_grid.tif
  # if tile_filter set TRUE
  # tile_filter_file should be set as well
  tile_filter: TRUE
  # one column named tile file
  tile_filter_file: qtiles_priority.csv
  output_encoding: utf-8
  catalog_filename: planet_catalog_db.csv
  catalog_path: catalog
  s3_bucket: activemapper
  s3_catalog_prefix: planet
  s3_composite_prefix: planet/composite_sr
  s3_analytic_sr_prefix: planet/analytic_sr_all
  prefix_geojson: ghana
  geojson_folder: geojson
  orderlist_folder: orderlist
  start_date: 2019-03-01
  end_date: 2019-03-05
  item: PSScene4Band
  asset: analytic_sr
  filter: TRUE
  clean: TRUE
  ## mode: 1 for initial, 2 for fix
  ## Fix mode doesn't save out the csvs
  mode: 1
  aws_cred: cfg/aws_cred.yml
  catalog_composite_s3: s3://activemapper/planet/catalogs

database:
  # test or production
  mode: test
  db_host: mapper0.crowdmapper.org
  db_password: 
  db_production_name: Africa
  db_sandbox_name: AfricaSandbox
  db_username: 

rasterfoundry:
  enabled: True
  api_key: 
  api_uri: app.rasterfoundry.com
  visibility: PRIVATE
  tileVisibility: PRIVATE
probability:
  s3_header: /vsis3
  s3_bucket: activemapper
  s3_tiff_perfix: classified-images/congo/
  s3_cogtiff_perfix: classified-images/congo_cog
  s3_catalog_prob: classified-images/probability_catalog_congo.csv

  