name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build containers
        run: docker-compose -f docker-compose.yml -f docker-compose.test.yml build
      - name: Start services that tests depend on
        run: docker-compose -f docker-compose.yml -f docker-compose.test.yml up -d franklin database && sleep 5
      - name: Run tests
        run: |
          docker-compose -f docker-compose.yml -f docker-compose.test.yml run python-test
